name: vvenv
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.10
  - pip
  - protobuf
  - mysql-connector-python
  - pyliftover>=0.3
  - numpy
  - httplib2>=0.9.0
  - configparser>=3.5.0
  - requests
