version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-mysql:
    docker:
      - image: ubuntu/mysql:8.0-22.04_beta
        ports:
          - "3306:3306"  # Expose the MySQL port
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "validator"
      MYSQL_USER: "vvadmin"
      MYSQL_PASSWORD: "var1ant"
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install necessary dependencies
          command: |
            apt-get update && apt-get install -y wget
          environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      - run:
          name: Download validator database dump
          command: |
            wget https://www528.lamp.le.ac.uk/vvdata/validator/validator_2023_08.sql.gz -O /docker-entrypoint-initdb.d/validator_2023_08.sql.gz

  build-postgres:
    docker:
      - image: postgres:14.7
        ports:
          - "5432:5432"  # Expose the PostgreSQL port
    environment:
      POSTGRES_DB: "vvta"
      POSTGRES_USER: "uta_admin"
      POSTGRES_PASSWORD: "uta_admin"
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install necessary dependencies
          command: |
            apt-get update && apt-get install -y wget
      - run:
          name: Download vvta database dump
          command: |
            wget https://www528.lamp.le.ac.uk/vvdata/vvta/vvta_2023_05_no_seq.sql.gz -O input_file.sql.gz
            gzip -dq input_file.sql.gz
            sed 's/anyarray/anycompatiblearray/g' input_file.sql > modified_file.sql
            rm input_file.sql
            gzip modified_file.sql
            mv modified_file.sql.gz /docker-entrypoint-initdb.d/vvta_2023_05_noseq.sql.gz

  build-and-test-vv:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: Create seqrepo directory
          command: mkdir -p ~/seqrepo
      - run:
          name: Download and extract Seqrepo data
          command: |
            wget --output-document=~/seqrepo/VV_SR_2023_05.tar https://www528.lamp.le.ac.uk/vvdata/vv_seqrepo/VV_SR_2023_05.tar
            tar -xvf ~/seqrepo/VV_SR_2023_05.tar --directory ~/seqrepo
      - run:
          name: Install dependencies
          command: pip install .
      - run:
          name: Copy configuration file
          command: cp configuration/continuous_integration.ini "$HOME"/.variantvalidator
          environment:
            HOME: /root
      - run:
          name: Wait for MySQL to become available
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Wait for PostgreSQL to become available
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run tests
          command: pytest
    environment:
      HOME: /root

workflows:
  version: 2
  variant_validator_ci:
    jobs:
      - build-mysql
      - build-postgres
      - build-and-test-vv:
          requires:
            - build-mysql
            - build-postgres
